#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Database1")]
	public partial class ContextoDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    partial void InsertENTIDADMADICO(ENTIDADMADICO instance);
    partial void UpdateENTIDADMADICO(ENTIDADMADICO instance);
    partial void DeleteENTIDADMADICO(ENTIDADMADICO instance);
    partial void InsertENTIDADESPECIALIDAD(ENTIDADESPECIALIDAD instance);
    partial void UpdateENTIDADESPECIALIDAD(ENTIDADESPECIALIDAD instance);
    partial void DeleteENTIDADESPECIALIDAD(ENTIDADESPECIALIDAD instance);
    partial void InsertENTIDADESPECIALIDADMEDICO(ENTIDADESPECIALIDADMEDICO instance);
    partial void UpdateENTIDADESPECIALIDADMEDICO(ENTIDADESPECIALIDADMEDICO instance);
    partial void DeleteENTIDADESPECIALIDADMEDICO(ENTIDADESPECIALIDADMEDICO instance);
    partial void InsertENTIDADESPECIALIDADPACIENTE(ENTIDADESPECIALIDADPACIENTE instance);
    partial void UpdateENTIDADESPECIALIDADPACIENTE(ENTIDADESPECIALIDADPACIENTE instance);
    partial void DeleteENTIDADESPECIALIDADPACIENTE(ENTIDADESPECIALIDADPACIENTE instance);
    partial void InsertENTIDADPACIENTEMEDICO(ENTIDADPACIENTEMEDICO instance);
    partial void UpdateENTIDADPACIENTEMEDICO(ENTIDADPACIENTEMEDICO instance);
    partial void DeleteENTIDADPACIENTEMEDICO(ENTIDADPACIENTEMEDICO instance);
    partial void InsertENTIDADPACIENTE(ENTIDADPACIENTE instance);
    partial void UpdateENTIDADPACIENTE(ENTIDADPACIENTE instance);
    partial void DeleteENTIDADPACIENTE(ENTIDADPACIENTE instance);
    #endregion
		
		public ContextoDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["Database1ConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public ContextoDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ContextoDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ContextoDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ContextoDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<ENTIDADMADICO> ENTIDADMADICO
		{
			get
			{
				return this.GetTable<ENTIDADMADICO>();
			}
		}
		
		public System.Data.Linq.Table<ENTIDADESPECIALIDAD> ENTIDADESPECIALIDAD
		{
			get
			{
				return this.GetTable<ENTIDADESPECIALIDAD>();
			}
		}
		
		public System.Data.Linq.Table<ENTIDADESPECIALIDADMEDICO> ENTIDADESPECIALIDADMEDICO
		{
			get
			{
				return this.GetTable<ENTIDADESPECIALIDADMEDICO>();
			}
		}
		
		public System.Data.Linq.Table<ENTIDADESPECIALIDADPACIENTE> ENTIDADESPECIALIDADPACIENTE
		{
			get
			{
				return this.GetTable<ENTIDADESPECIALIDADPACIENTE>();
			}
		}
		
		public System.Data.Linq.Table<ENTIDADPACIENTEMEDICO> ENTIDADPACIENTEMEDICO
		{
			get
			{
				return this.GetTable<ENTIDADPACIENTEMEDICO>();
			}
		}
		
		public System.Data.Linq.Table<ENTIDADPACIENTE> ENTIDADPACIENTE
		{
			get
			{
				return this.GetTable<ENTIDADPACIENTE>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Medicos")]
	public partial class ENTIDADMADICO : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _DNI;
		
		private string _Nombre;
		
		private string _Especialidad;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnDNIChanging(string value);
    partial void OnDNIChanged();
    partial void OnNombreChanging(string value);
    partial void OnNombreChanged();
    partial void OnEspecialidadChanging(string value);
    partial void OnEspecialidadChanged();
    #endregion
		
		public ENTIDADMADICO()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DNI", DbType="VarChar(50)")]
		public string DNI
		{
			get
			{
				return this._DNI;
			}
			set
			{
				if ((this._DNI != value))
				{
					this.OnDNIChanging(value);
					this.SendPropertyChanging();
					this._DNI = value;
					this.SendPropertyChanged("DNI");
					this.OnDNIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="VarChar(50)")]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this.OnNombreChanging(value);
					this.SendPropertyChanging();
					this._Nombre = value;
					this.SendPropertyChanged("Nombre");
					this.OnNombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Especialidad", DbType="VarChar(50)")]
		public string Especialidad
		{
			get
			{
				return this._Especialidad;
			}
			set
			{
				if ((this._Especialidad != value))
				{
					this.OnEspecialidadChanging(value);
					this.SendPropertyChanging();
					this._Especialidad = value;
					this.SendPropertyChanged("Especialidad");
					this.OnEspecialidadChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Especialidades")]
	public partial class ENTIDADESPECIALIDAD : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _Nombre;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnNombreChanging(string value);
    partial void OnNombreChanged();
    #endregion
		
		public ENTIDADESPECIALIDAD()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="VarChar(50)")]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this.OnNombreChanging(value);
					this.SendPropertyChanging();
					this._Nombre = value;
					this.SendPropertyChanged("Nombre");
					this.OnNombreChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.[Especialidad-Medico]")]
	public partial class ENTIDADESPECIALIDADMEDICO : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _Nombre_Especialidad;
		
		private string _DNI_Medico;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnNombre_EspecialidadChanging(string value);
    partial void OnNombre_EspecialidadChanged();
    partial void OnDNI_MedicoChanging(string value);
    partial void OnDNI_MedicoChanged();
    #endregion
		
		public ENTIDADESPECIALIDADMEDICO()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre_Especialidad", DbType="VarChar(50)")]
		public string Nombre_Especialidad
		{
			get
			{
				return this._Nombre_Especialidad;
			}
			set
			{
				if ((this._Nombre_Especialidad != value))
				{
					this.OnNombre_EspecialidadChanging(value);
					this.SendPropertyChanging();
					this._Nombre_Especialidad = value;
					this.SendPropertyChanged("Nombre_Especialidad");
					this.OnNombre_EspecialidadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DNI_Medico", DbType="VarChar(50)")]
		public string DNI_Medico
		{
			get
			{
				return this._DNI_Medico;
			}
			set
			{
				if ((this._DNI_Medico != value))
				{
					this.OnDNI_MedicoChanging(value);
					this.SendPropertyChanging();
					this._DNI_Medico = value;
					this.SendPropertyChanged("DNI_Medico");
					this.OnDNI_MedicoChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.[Especialidad-Paciente]")]
	public partial class ENTIDADESPECIALIDADPACIENTE : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _Nombre_Especialidad;
		
		private string _DNI_Paciente;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnNombre_EspecialidadChanging(string value);
    partial void OnNombre_EspecialidadChanged();
    partial void OnDNI_PacienteChanging(string value);
    partial void OnDNI_PacienteChanged();
    #endregion
		
		public ENTIDADESPECIALIDADPACIENTE()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre_Especialidad", DbType="VarChar(50)")]
		public string Nombre_Especialidad
		{
			get
			{
				return this._Nombre_Especialidad;
			}
			set
			{
				if ((this._Nombre_Especialidad != value))
				{
					this.OnNombre_EspecialidadChanging(value);
					this.SendPropertyChanging();
					this._Nombre_Especialidad = value;
					this.SendPropertyChanged("Nombre_Especialidad");
					this.OnNombre_EspecialidadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DNI_Paciente", DbType="VarChar(50)")]
		public string DNI_Paciente
		{
			get
			{
				return this._DNI_Paciente;
			}
			set
			{
				if ((this._DNI_Paciente != value))
				{
					this.OnDNI_PacienteChanging(value);
					this.SendPropertyChanging();
					this._DNI_Paciente = value;
					this.SendPropertyChanged("DNI_Paciente");
					this.OnDNI_PacienteChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.[Paciente-Medico]")]
	public partial class ENTIDADPACIENTEMEDICO : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _DniPaciente;
		
		private string _DniMedico;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnDniPacienteChanging(string value);
    partial void OnDniPacienteChanged();
    partial void OnDniMedicoChanging(string value);
    partial void OnDniMedicoChanged();
    #endregion
		
		public ENTIDADPACIENTEMEDICO()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DniPaciente", DbType="VarChar(50)")]
		public string DniPaciente
		{
			get
			{
				return this._DniPaciente;
			}
			set
			{
				if ((this._DniPaciente != value))
				{
					this.OnDniPacienteChanging(value);
					this.SendPropertyChanging();
					this._DniPaciente = value;
					this.SendPropertyChanged("DniPaciente");
					this.OnDniPacienteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DniMedico", DbType="VarChar(50)")]
		public string DniMedico
		{
			get
			{
				return this._DniMedico;
			}
			set
			{
				if ((this._DniMedico != value))
				{
					this.OnDniMedicoChanging(value);
					this.SendPropertyChanging();
					this._DniMedico = value;
					this.SendPropertyChanged("DniMedico");
					this.OnDniMedicoChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Pacientes")]
	public partial class ENTIDADPACIENTE : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _DNI;
		
		private string _Nombre;
		
		private System.Nullable<System.DateTime> _FechaNac;
		
		private string _Sexo;
		
		private System.Nullable<int> _ninternacion;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnDNIChanging(string value);
    partial void OnDNIChanged();
    partial void OnNombreChanging(string value);
    partial void OnNombreChanged();
    partial void OnFechaNacChanging(System.Nullable<System.DateTime> value);
    partial void OnFechaNacChanged();
    partial void OnSexoChanging(string value);
    partial void OnSexoChanged();
    partial void OnninternacionChanging(System.Nullable<int> value);
    partial void OnninternacionChanged();
    #endregion
		
		public ENTIDADPACIENTE()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DNI", DbType="VarChar(50)")]
		public string DNI
		{
			get
			{
				return this._DNI;
			}
			set
			{
				if ((this._DNI != value))
				{
					this.OnDNIChanging(value);
					this.SendPropertyChanging();
					this._DNI = value;
					this.SendPropertyChanged("DNI");
					this.OnDNIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="VarChar(50)")]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this.OnNombreChanging(value);
					this.SendPropertyChanging();
					this._Nombre = value;
					this.SendPropertyChanged("Nombre");
					this.OnNombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaNac", DbType="DateTime2")]
		public System.Nullable<System.DateTime> FechaNac
		{
			get
			{
				return this._FechaNac;
			}
			set
			{
				if ((this._FechaNac != value))
				{
					this.OnFechaNacChanging(value);
					this.SendPropertyChanging();
					this._FechaNac = value;
					this.SendPropertyChanged("FechaNac");
					this.OnFechaNacChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sexo", DbType="VarChar(50)")]
		public string Sexo
		{
			get
			{
				return this._Sexo;
			}
			set
			{
				if ((this._Sexo != value))
				{
					this.OnSexoChanging(value);
					this.SendPropertyChanging();
					this._Sexo = value;
					this.SendPropertyChanged("Sexo");
					this.OnSexoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ninternacion", DbType="Int")]
		public System.Nullable<int> ninternacion
		{
			get
			{
				return this._ninternacion;
			}
			set
			{
				if ((this._ninternacion != value))
				{
					this.OnninternacionChanging(value);
					this.SendPropertyChanging();
					this._ninternacion = value;
					this.SendPropertyChanged("ninternacion");
					this.OnninternacionChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
